# Generated by Django 4.0.6 on 2022-08-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=11)),
                ('last_name', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('p', 'male'), ('m', 'female')], max_length=6, null=True)),
                ('nationality', models.CharField(max_length=11, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
    ]
